### ISSUE TITLE
isar_flutter_libs 3.1.8 which doesn't match any versions

### ISSUE THREAD

**Issue by UnluckyY1** [isar-community/isar#98] opened 2024-08-13 09:01 UTC
```
Resolving dependencies...
Because xxx depends on isar_flutter_libs 3.1.8 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on isar_flutter_libs: flutter pub add isar_flutter_libs:'{"version":"^3.1.7","hosted":"https://pub.isar-community.dev"}'
exit code 1

```

**Comment by UnluckyY1** [comment] 2024-08-13 09:49
I’ve tried to override the dependency directly from Git, but now iOS builds are failing.

```
isar_flutter_libs: # contains Isar Core
    git:
      url: https://github.com/isar-community/isar.git
      path: packages/isar_flutter_libs
      ref: 8aab130
```

```

Error (Xcode): Undefined symbol: _isar_get_error


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while building for device.
```

**Comment by brim-borium** [comment] 2024-08-13 11:08
I think the issue is that this action failed: https://github.com/isar-community/isar/actions/runs/10366248627, which should release the 3.1.8 version. Maybe @mrclauss can have a look?

**Comment by mrclauss** [comment] 2024-08-13 18:11
Yes, the binaries are not on binaries.isar-community.dev, I asked @vicenterusso if he knows why the upload failed...

**Comment by mrclauss** [comment] 2024-08-13 18:34
Fixed by manually downloading the release artifacts and publishing them

**Closed** 2024-08-13 18:34 UTC

**Comment by mrclauss** [comment] 2024-08-13 18:36
> I’ve tried to override the dependency directly from Git, but now iOS builds are failing.
> 
> ```
> isar_flutter_libs: # contains Isar Core
>     git:
>       url: https://github.com/isar-community/isar.git
>       path: packages/isar_flutter_libs
>       ref: 8aab130
> ```
> 
> ```
> 
> Error (Xcode): Undefined symbol: _isar_get_error
> 
> 
> Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
> 
> 
> Encountered error while building for device.
> ```

Overriding from git(hub) doesn't work, because this does not actually build the binary libraries locally
