### ISSUE TITLE
Isar inspector returning 404

### ISSUE THREAD

**Issue by JCKodel** [isar-community/isar#81] opened 2024-05-07 18:08 UTC
### Steps to Reproduce

After updating to Isar 4.0.3, those links:

![image](https://github.com/isar-community/isar/assets/379339/d76d38a3-47ea-459e-bc62-41a1e0891232)

results in 

![image](https://github.com/isar-community/isar/assets/379339/3832a193-5ecf-4752-9de5-7c2faecc4410)

### Details

 - Platform: Android
 - Flutter version: 3.19.6
 - Isar version: 4.0.3

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by nobkd** [comment] 2024-05-07 18:20
Duplicate of #72. Already fixed in code, but not published.

See  to fix it on local

**Comment by JCKodel** [comment] 2024-05-07 18:53
> Duplicate of #72. Probably already fixed in code, but not published? (not sure, because the code change there was for v3) [#72 (comment)](https://github.com/isar-community/isar/issues/72#issuecomment-2096415473) might work to fix it on local

Ok, but notice that the workaround does NOT work on 4.0.3. Changing the URL to [https://inspect.isar-community.dev/${Isar.version}/#/$port$path](https://inspect.isar-community.dev/$%7BIsar.version%7D/#/$port$path) does NOT work.

**Comment by vicenterusso** [comment] 2024-05-09 14:45
This should be fixed now. Just click the link displayed by the console log.

Old inspector URLs are being redirected to new place (`inspect.isar-community.dev`).

**Closed by vicenterusso** 2024-05-09 14:45 UTC
